# Generated by Django 4.0.2 on 2022-03-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_remove_project_taskassign_employee_files_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_taskassign',
            old_name='files',
            new_name='employee_files',
        ),
    ]
