# Generated by Django 4.0.2 on 2022-03-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_rename_files_project_taskassign_employee_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_taskassign',
            name='json_screenshot',
        ),
        migrations.AddField(
            model_name='branch_registration',
            name='email',
            field=models.EmailField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='branch_registration',
            name='logo',
            field=models.FileField(default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='branch_registration',
            name='mobile',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='project_taskassign',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
